const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
  const p = await b.newPage({viewport:{width:1180,height:820}});
  const errors = []; p.on('pageerror', e => errors.push(e.message)); p.on('console', m => { if (m.type()==='error' && !/CERT|google|net::|voice\//.test(m.text())) errors.push(m.text()); });
  await p.goto('http://localhost:8765/next/landscape/?stage=eschool', {waitUntil:'networkidle'}); await p.evaluate(() => { try{ localStorage.clear(); }catch(e){} }); await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(900); if (!(await p.evaluate(() => document.getElementById('comic').hidden))) await p.click('#cskip'); await p.waitForTimeout(300);
  console.log('child', await p.evaluate(() => CHILD), 'card hidden?', await p.evaluate(() => document.getElementById('stagecard').hidden)); await p.screenshot({path:'pe-card.png'});
  await p.click('#cardGo'); await p.waitForTimeout(300);
  const st = () => p.evaluate(() => ({room:S.room, view:S.view, got:S.got.join(','), placed:S.placed.join(','), cogs:S.cogs.join(''), card:S.cardRead, chalk:S.chalkSeen, peg:S.pegSeen, bell:S.bell, done:S.done}));
  const msg = () => p.textContent('#msg');
  const tap = async (id, wait=400) => { const n = await p.locator(`.hs[data-id="${id}"]`).count(); if (!n){ console.log('NO HOTSPOT', id, JSON.stringify(await st())); return; } await p.click(`.hs[data-id="${id}"]`, {force:true}); await p.waitForTimeout(wait); };
  const turnTo = async (view) => { for (let i=0;i<5;i++){ const v = await p.evaluate(() => ROOMS[S.room].views[S.view]); if (v===view) return; await p.click('#right'); await p.waitForTimeout(320); } console.log('could not turn to', view); };
  const go = async (id) => { await tap(id, 1600); };
  const back = async () => { await p.keyboard.press('Escape'); await p.waitForTimeout(250); };
  const hold = async (name) => { await p.click(`.slot[aria-label="${name}"]`); await p.waitForTimeout(150); };
  const noOverflow = async (label) => { const r = await p.evaluate(() => { const c = document.querySelector('#closeup .card'); if (!c) return 'no card'; const cu = document.querySelector('#closeup').getBoundingClientRect(), r = c.getBoundingClientRect(); return (c.scrollHeight > c.clientHeight + 1 || c.scrollWidth > c.clientWidth + 1) ? 'inner' : (r.bottom > cu.bottom + 1 || r.right > cu.right + 1 ? 'outer' : false); }); if (r !== false) console.log('OVERFLOW?', label, r); };
  const shot = async (n) => p.screenshot({path:`pe-${n}.png`});
  console.log('start', JSON.stringify(await st())); await shot('p1');
  await tap('e_card', 800); await noOverflow('card'); await shot('cardnote'); await back(); console.log('card read', JSON.stringify(await st()));
  await tap('e_card', 800); console.log('card again:', await msg()); await back();
  await turnTo('p2'); await shot('p2'); await tap('e_tank', 600); await shot('notebook'); await noOverflow('notebook'); console.log('nb title:', await p.textContent('#closeup .head')); await p.click('.nbrow[data-i="1"]'); await p.waitForTimeout(200); console.log('hint:', await p.textContent('#nbFb')); await back();
  await tap('e_run', 700); await noOverflow('run'); await shot('run-empty'); console.log('run:', await p.textContent('#runFb')); await p.click('#runpic .gap[data-i="0"]'); await p.waitForTimeout(200); console.log('gap no piece:', await p.textContent('#runFb')); await back();
  await tap('e_tray'); console.log('tray:', await msg(), JSON.stringify(await st()));
  await hold('straight piece'); await tap('e_run', 700); await p.click('#runpic .gap[data-i="1"]'); await p.waitForTimeout(200); console.log('wrong gap:', await p.textContent('#runFb')); await p.click('#runpic .gap[data-i="0"]'); await p.waitForTimeout(700); console.log('placed:', JSON.stringify(await st()), 'roll?', await p.locator('#roll').count()); await shot('run-1'); await back();
  await turnTo('p3'); await shot('p3'); await tap('e_pegs', 700); await noOverflow('pegs'); await shot('pegs'); await back(); console.log('pegs:', await msg());
  await turnTo('p4'); await shot('p4'); await tap('e_cog1', 300); console.log('cog:', await msg());
  await turnTo('p3'); await go('e_out'); console.log('out', JSON.stringify(await st())); await shot('g1');
  await tap('e_box', 700); await noOverflow('box'); await shot('box'); await p.click('#boxpic .book[data-i="0"]'); await p.waitForTimeout(200); console.log('cat:', await p.textContent('#boxFb')); await p.click('#boxpic .book[data-i="1"]'); await p.waitForTimeout(1300); console.log('rocket:', await p.textContent('#boxFb'), 'zig btn?', await p.locator('#takeZig').count()); await shot('box2'); await p.click('#takeZig'); await p.waitForTimeout(400); console.log('zig:', await msg(), JSON.stringify(await st()));
  await tap('e_cog2', 300);
  await turnTo('g2'); await shot('g2'); await tap('e_sandpit'); console.log('sand:', await msg());
  await turnTo('g3'); await shot('g3'); await tap('e_cog3', 300); console.log('cogs:', JSON.stringify(await st()));
  await turnTo('g4'); await shot('g4'); await tap('e_chalk', 700); await noOverflow('chalk'); await shot('chalk'); await back();
  await turnTo('g3'); await go('e_in'); console.log('in', JSON.stringify(await st()));
  await turnTo('p2'); await hold('curved piece'); await tap('e_run', 700); await p.click('#runpic .gap[data-i="1"]'); await p.waitForTimeout(700); await back();
  await hold('zigzag piece'); await tap('e_run', 700); await p.click('#runpic .gap[data-i="2"]'); await p.waitForTimeout(700); console.log('all in:', JSON.stringify(await st()), 'roll?', await p.locator('#roll').count()); await shot('run-3');
  await p.click('#roll'); await p.waitForTimeout(2200); await shot('rolling'); await p.waitForTimeout(3000); console.log('bell:', JSON.stringify(await st()), await msg()); await shot('after-roll');
  await turnTo('p1'); await tap('e_card', 1200); await noOverflow('cardopen'); await shot('cardopen'); await p.waitForTimeout(6500); await shot('end'); console.log('end shown?', !(await p.evaluate(() => document.getElementById('endUI').hidden)), await p.textContent('#endTitle'), (await p.textContent('.postcard .pmsg')).slice(0,80));
  console.log('errors', errors);
  await b.close();
})();
